ALTER TABLE usuarios
ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE,
ADD COLUMN IF NOT EXISTS equipo_tratante VARCHAR(150),
ADD COLUMN IF NOT EXISTS estado_motivacional VARCHAR(120),
ADD COLUMN IF NOT EXISTS programa VARCHAR(150);

ALTER TABLE usuarios DROP COLUMN IF EXISTS descripcion;